-- 建立 SERVERMANAGEFUNCTION（後台管理功能）表
CREATE TABLE SERVERMANAGEFUNCTION (
    SMGEFUNC_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SMGEFUNC VARCHAR(45) NOT NULL
);

-- 建立 SERVERMANAGER（後台管理員）表
CREATE TABLE SERVERMANAGER (
    SMGR_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SMGR_EMAIL VARCHAR(45) NOT NULL,
    SMGR_ACCOUNT VARCHAR(45) NOT NULL UNIQUE,
    SMGR_PASSWORD VARCHAR(128) NOT NULL,
    SMGR_NAME VARCHAR(45) NOT NULL,
    SMGR_PHONE VARCHAR(10) NOT NULL,
    SMGR_STATUS TINYINT  NOT NULL DEFAULT 1 COMMENT '0:停權,1:正常使用'
);

-- 建立 SERVERMANAGERAUTH（後台管理員權限）表
CREATE TABLE SERVERMANAGERAUTH (
    SMGEFUNC_ID INT NOT NULL,
    SMGR_ID INT NOT NULL,
    PRIMARY KEY (SMGEFUNC_ID, SMGR_ID),
    FOREIGN KEY (SMGEFUNC_ID) REFERENCES SERVERMANAGEFUNCTION(SMGEFUNC_ID),
    FOREIGN KEY (SMGR_ID) REFERENCES SERVERMANAGER(SMGR_ID)
);

-- 建立 APPROPRIATION_COMM_RECORD（平台撥款及佣金紀錄）表
CREATE TABLE APPROPRIATION_COMM_RECORD (
    COMM_PAYOUT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ORDER_TYPE TINYINT NOT NULL COMMENT '0:一般訂單, 1:團購訂單',
    ORDER_REF_ID INT NOT NULL,
    STOR_ID INT NULL,
    MEM_ID INT NULL,
    PAYOUT_ROLE TINYINT NOT NULL COMMENT '0:商家, 1:團主',
    PAYOUT_AMOUNT DECIMAL(10,2) NULL,
    COMMISSION_AMOUNT DECIMAL(10,2) NULL,
    PAYOUT_STATUS TINYINT NOT NULL COMMENT '0:等待撥款, 1:已撥款',
    COMMISSION_STATUS TINYINT NOT NULL COMMENT '0:等待撥款, 1:已撥款',
    CREATE_AT DATETIME NOT NULL,
    UPDATE_AT DATETIME NOT NULL,
    PAYOUT_TIME DATETIME NULL,
    PAYOUT_MONTH VARCHAR(6) NULL,
    FOREIGN KEY (STOR_ID) REFERENCES STORE(STOR_ID),
    FOREIGN KEY (MEM_ID) REFERENCES MEMBER(MEM_ID),
    INDEX (ORDER_REF_ID)
);

CREATE TABLE GB_PROD_CATEGORY (
    GB_CATE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  -- 商品類別編號 (主鍵，自動編號)
    GB_CATE_NAME VARCHAR(45) NOT NULL                    -- 商品類別名稱
);
CREATE TABLE GROUP_PRODUCTS (
    GB_PROD_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,                   
    STOR_ID INT NOT NULL,                                                 
    GB_CATE_ID INT NOT NULL,                                              
    GB_PROD_NAME VARCHAR(45) NOT NULL,                                    
    GB_PROD_DESCRIPTION VARCHAR(45) NOT NULL,                           
    GB_PROD_QUANTITY INT NOT NULL,                                        
    GB_PROD_STATUS TINYINT NOT NULL,                                      
    UPDATE_AT DATETIME NOT NULL,                                          
    GB_PROD_SPECIFICATION VARCHAR(45) NOT NULL,                           
    PROD_PHOTO LONGBLOB,                                                  
    GB_PROD_EVALUATE VARCHAR(45),                                        
    GB_PROD_REPORT_COUNT TINYINT UNSIGNED NOT NULL,                       

    FOREIGN KEY (STOR_ID) REFERENCES STORE(STOR_ID),                      
    FOREIGN KEY (GB_CATE_ID) REFERENCES GB_PROD_CATEGORY(GB_CATE_ID)     
);
CREATE TABLE GB_PROMOTION (
    GB_PROMO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    GB_PROD_ID INT NOT NULL,                             
    GB_MIN_QTY INT NOT NULL,                             
    PROMT_START DATETIME NOT NULL,                       
    PROMT_END DATETIME NOT NULL,                         
    GB_PROD_SALES INT NOT NULL,                         
    GB_PROD_SPE INT NOT NULL,                            -- 商家優惠價
    FOREIGN KEY (GB_PROD_ID) REFERENCES GROUP_PRODUCTS(GB_PROD_ID)
);


